name: "TidyBot"
description: "Daily code tidy-up using OpenAI and style guides"
author: "your-username"
inputs:
  openai_api_key:
    description: "Your OpenAI API key"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "edit"
  color: "blue"
